### PR TITLE
add pytest

### PR DESCRIPTION
**Pull request by TahaBinhuraib**

### CODE REVIEW

**Comment by TahaBinhuraib** [comment]
Initiate pytest to work with @merveenoyan's workflow

**Comment by TahaBinhuraib** [comment]
@merveenoyan can you add the keys to github settings? 
we also need a test.yml file that sets environments. Here is an example:
` env:
          OPENAI_API_KEY_POOL: ${{ secrets.key }}`

**Comment by merveenoyan** [comment]
@TahaBinhuraib I've handed our environmental variables to cloud folks, they will modify the github actions accordingly.

**Comment by ekinakyurek** [comment]
Hi Merve,

Can you share them privately with me? I just want to make sure whether they
are correct and my google geocoding is not exposed.

**Comment by merveenoyan** [comment]
@ekinakyurek I've only given them OpenAI base and key pools, nothing about geocoding.

**Pull request merged**
